from app.models.permission import Permission
from app.models.role import Role
from app.models.colors import Color
from app.models.configuration import Configuration
from app.models.meeting_point import MeetingPoint
from app.models.user import User
from app.models.coordinate import Coordinate
from app.models.flood_zones import FloodZones
from app.models.evacuation_route import EvacuationRoute
from app.models.complaint import Complaint
from app.models.category import Category
from app.models.complaint_follow_up import ComplaintFollowUp